import { Router } from "express";
import { userRoutes } from "./userRoutes";
import { applicantRoutes } from "./applicantRoutes";
import { groupRoutes } from "./groupRoutes";
import { formRoutes } from "./formRoutes";
import { auditRoutes } from "./auditRoutes";
import { veterinarianVisitRoutes } from "./veterinarianVisitRoutes";
import { veterinarianSampleRoutes } from "./veterinarianSampleRoutes";
import { physicalExamRoutes } from "./physicalExamRoutes";
import { vaccineRoutes } from "./vaccineRoutes";
import { examResultRoutes } from "./examResultRoutes";
import { sorologyResultRoutes } from "./sorologyResultRoutes";
import { ectoparasiteAnalysisRoutes } from "./ectoparasiteAnalysisRoutes";
import { stoolAnalysisRoutes } from "./stoolAnalysisRoutes";
import { eggCystAnalysisRoutes } from "./eggCystAnalysisRoutes";
import { molecularAnalysisRoutes } from "./molecularAnalysisRoutes";
import { gpsTrackingRoutes } from "./gpsTrackingRoutes";
import { interviewRoutes } from "./interviewRoutes";
import { liveAnimalRoutes } from "./liveAnimalRoutes";
import { castrationRoutes } from "./castrationRoutes";
import { tutorRoutes } from "./tutorRoutes";
import { deadAnimalRoutes } from "./deadAnimalRoutes";
import { necropsyRoutes } from "./necropsyRoutes";
import { necropsySampleRoutes } from "./necropsySampleRoutes";
import { basicRegistrationRoutes } from "./basicRegistrationRoutes";
import { necropsyEctoparasiteAnalysisRoutes } from "./necropsyEctoparasiteAnalysisRoutes";
import { helminthAnalysisRoutes } from "./helminthAnalysisRoutes";
import { necropsyExamResultRoutes } from "./necropsyExamResultRoutes";

export const router = Router();

router.use(userRoutes);
router.use(applicantRoutes);
router.use(groupRoutes);
router.use(formRoutes);
router.use(auditRoutes);
router.use(veterinarianVisitRoutes);
router.use(veterinarianSampleRoutes);
router.use(physicalExamRoutes);
router.use(vaccineRoutes);
router.use(examResultRoutes);
router.use(sorologyResultRoutes);
router.use(ectoparasiteAnalysisRoutes);
router.use(stoolAnalysisRoutes);
router.use(eggCystAnalysisRoutes);
router.use(molecularAnalysisRoutes);
router.use(gpsTrackingRoutes);
router.use(interviewRoutes);
router.use(liveAnimalRoutes);
router.use(castrationRoutes);
router.use(tutorRoutes);
router.use(deadAnimalRoutes);
router.use(necropsyRoutes);
router.use(necropsySampleRoutes);
router.use(basicRegistrationRoutes);
router.use(necropsyEctoparasiteAnalysisRoutes);
router.use(helminthAnalysisRoutes);
router.use(necropsyExamResultRoutes);

import { seedQuestions } from "../scripts/seed-questions";
router.post('/temp/seed-questions', async (req, res) => {
    await seedQuestions();
    res.json({ message: 'Questions seeded successfully' });
});
