import { Router } from "express";
import { userRoutes } from "./userRoutes";
import { applicantRoutes } from "./applicantRoutes";
import { groupRoutes } from "./groupRoutes";
import { formRoutes } from "./formRoutes";
import { auditRoutes } from "./auditRoutes";
import { veterinarianVisitRoutes } from "./veterinarianVisitRoutes";
import { veterinarianSampleRoutes } from "./veterinarianSampleRoutes";
import { physicalExamRoutes } from "./physicalExamRoutes";
import { vaccineRoutes } from "./vaccineRoutes";
import { examResultRoutes } from "./examResultRoutes";
import { sorologyResultRoutes } from "./sorologyResultRoutes";
import { ectoparasiteAnalysisRoutes } from "./ectoparasiteAnalysisRoutes";
import { stoolAnalysisRoutes } from "./stoolAnalysisRoutes";
import { eggCystAnalysisRoutes } from "./eggCystAnalysisRoutes";
import { molecularAnalysisRoutes } from "./molecularAnalysisRoutes";

export const router = Router();

router.use(userRoutes);
router.use(applicantRoutes);
router.use(groupRoutes);
router.use(formRoutes);
router.use(auditRoutes);
router.use(veterinarianVisitRoutes);
router.use(veterinarianSampleRoutes);
router.use(physicalExamRoutes);
router.use(vaccineRoutes);
router.use(examResultRoutes);
router.use(sorologyResultRoutes);
router.use(ectoparasiteAnalysisRoutes);
router.use(stoolAnalysisRoutes);
router.use(eggCystAnalysisRoutes);
router.use(molecularAnalysisRoutes);
